update reward and add getReward API
Evanesco-Labs/go-evanesco pull request #29
Opened 2021-11-26 05:37 UTC by hanbaofu

2021-11-26 05:38 UTC, hanbaofu commented
Update reward and add getReward API

2021-12-07 05:49 UTC, calehh requested changes
reset unrelated changes

2021-12-07 05:49 UTC, calehh commented on evaclient/evaclient.go
> +	ethereum "github.com/Evanesco-Labs/go-evanesco"
remove this change

2021-12-07 05:49 UTC, calehh commented on internal/ethapi/api.go
> +	"github.com/davecgh/go-spew/spew"
reset this change

2021-12-09 00:41 UTC, merged